version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.12.5
    - 5.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
